import { promises as fs } from "fs";
import path from "path";
import { rimraf } from "rimraf";
import { registryItemFileSchema } from "../../registry/schema";
import { z } from "zod";

import { registry } from "../../registry/index";

const REGISTRY_BASE_PATH = "registry";
const PUBLIC_FOLDER_BASE_PATH = "public/r";

async function buildRegistryIndex() {
  let index = `/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {`;
  for (const item of registry.items) {
    const resolveFiles = item.files?.map(
      (file) => `${REGISTRY_BASE_PATH}/${file.path}`
    );
    if (!resolveFiles) {
      continue;
    }

    const componentPath = item.files?.[0]?.path
      ? `@/${REGISTRY_BASE_PATH}/${item.files[0].path}`
      : "";

    // Read file contents for each file
    const fileContent = item.files
      ? await Promise.all(
          item.files.map(async (file) => {
            const filePath = `${REGISTRY_BASE_PATH}/${file.path}`;
            let code = "";
            try {
              code = await fs.readFile(filePath, "utf-8");
            } catch (e) {
              code = "";
            }
            return JSON.stringify(code);
          })
        )
      : [];

    index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ""}",
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
    content: [${fileContent.join(",")}],
    component: ${
      componentPath
        ? `React.lazy(async () => {
      const mod = await import("${componentPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    })`
        : "null"
    },
    categories: ${JSON.stringify(item.categories)},
    meta: ${JSON.stringify(item.meta)},
  },`;
  }

  index += `
  }`;

  console.log(`#️⃣  ${Object.keys(registry.items).length} components found`);

  // Write style index.
  rimraf.sync(path.join(process.cwd(), "registry/__index__.tsx"));
  await fs.writeFile(path.join(process.cwd(), "registry/__index__.tsx"), index);
}

// ----------------------

async function buildRegistryJsonFilesCustom() {
  for (let i = 0; i < registry?.items?.length; i++) {
    const component = registry.items[i];
    const files = component.files;
    if (!files) throw new Error("No files found for component");

    const filesArray = await getComponentFiles(files);

    const json = JSON.stringify(
      {
        ...component,
        files: filesArray,
      },
      null,
      2
    );
    const jsonPath = `${PUBLIC_FOLDER_BASE_PATH}/${component.name}.json`;
    await writeFileRecursive(jsonPath, json);
  }
}

async function writeFileRecursive(filePath: string, data: string) {
  const dir = path.dirname(filePath); // Extract the directory path

  try {
    // Ensure the directory exists, recursively creating directories as needed
    await fs.mkdir(dir, { recursive: true });

    // Write the file
    await fs.writeFile(filePath, data, "utf-8");
    console.log(`File written to ${filePath}`);
  } catch (error) {
    console.error(`Error writing file`);
    console.error(error);
  }
}

const getComponentFiles = async (
  files: z.infer<typeof registryItemFileSchema>[]
) => {
  const filesArrayPromises = (files ?? []).map(async (file) => {
    // file is an object with path, type, and maybe target
    const filePath = `${REGISTRY_BASE_PATH}/${file.path}`;
    const fileContent = await fs.readFile(filePath, "utf-8");
    return {
      type: file.type,
      content: fileContent,
      path: file.path,
      // target: file.target ? `${COMPONENT_FOLDER_PATH}/${file.target}`:file.path,
      target: file.target ?? file.path,
    };
  });
  const filesArray = await Promise.all(filesArrayPromises);

  return filesArray;
};

try {
  console.log("🗂️ Building registry/__index__.tsx...");
  await buildRegistryIndex();

  console.log("🗂️ Building registry json files...");
  await buildRegistryJsonFilesCustom();
} catch (error) {
  console.error(error);
  process.exit(1);
}
